### ISSUE TITLE
Log Watcher Error

### ISSUE THREAD

**Issue by jamiecwong** [jhuckaby/Cronicle#117]
## Summary

Hi there,
Log Watcher is throwing an error:
```Log Watcher: Server Connect Error: Error: websocket error (https://ipaddress:3013)```

Thanks!

## Your Setup

Okay so I have an instance in AWS running cronicle, which is behind a loadbalancer, the loadbalancer listens on https and then directs the traffic to the cronicle server on port 3012 (so http).

Is there anyway to get the Log Watcher to connect on http port 3012?

### Operating system and version?

Centos 7.5

### Node.js version?

10.9.0

### Cronicle software version?

Version 0.8.28

### Are you using a multi-server setup, or just a single server?

Single server

### Are you using the filesystem as back-end storage, or S3/Couchbase?

Filesystem

### Can you reproduce the crash consistently?

Yes

## Log Excerpts

```Log Watcher: Server Connect Error: Error: websocket error (https://ipaddress:3013)```

**Comment by jhuckaby** [comment]
The only reason Cronicle would ever try to connect on port 3013 is if you have enabled HTTPS (SSL) in the main web server configuration.  Since this isn't officially supported yet, and you seem to be doing HTTPS in your load balancer anyway, you should disable it in Cronicle.  Set `https` to false here:

```js
{
	"WebServer": {
		"http_port": 3012,
		"https": false
	}
}
```

That should prevent it trying to connect on port 3013.

Proper HTTPS / SSL support is coming in a future release.

**Comment by jamiecwong** [comment]
Thanks for the reply.

I do have https set to false but I get the same error. Could it be that the load balancer I am using is https and therefore the connection from client machine assumes https?

Another thing I noticed - if i connect to the UI on the local IP (http) the log watcher successfully connects back to the sever in http. However I see no output until the job completes running, so no live logging, have you seen this before?

Thanks for all your help.
