### ISSUE TITLE
Network Error: 500: An unknown network error occurred. Please try again.

### ISSUE THREAD

**Issue by oMikR0n** [jhuckaby/Cronicle#15]
I tried setup cronicle but i think i have network related issues! Can you please help?
I get this when tried to login : 

   Network Error: 500: An unknown network error occurred. Please try again.

**Comment by jhuckaby** [comment]
I'm sorry, but there are so many different things that could be going wrong here, I have no idea what to tell you or where to start.  Given only this error message, and no context of how you have your server(s) configured or your network architecture, I have no idea how I could possibly help.

All I can suggest is that you read these sections of the docs, specifically keeping in mind that Cronicle connects using the server's LAN IP, so you need a network route to that.  Cronicle will not work with cloud-based servers (Amazon EC2, et al) out of the box, unless you are connected to a VPN, or you reconfigure the server to have a public hostname in DNS, property routed with a public IP, and change some configuration parameters around.

https://github.com/jhuckaby/Cronicle#server_comm_use_hostnames

### server_comm_use_hostnames

Setting this parameter to `1` will force the Cronicle servers to connect to each other using hostnames rather than LAN IP addresses.  This is mainly for special situations where your local server IP addresses may change, and you would prefer to rely on DNS instead.  The default is `0` (disabled), meaning connect using IP addresses.

https://github.com/jhuckaby/Cronicle#web_socket_use_hostnames

### web_socket_use_hostnames

Setting this parameter to `1` will force Cronicle's Web UI to connect to the back-end servers using their hostnames rather than IP addresses.  This includes both AJAX API calls and Websocket streams.  You should only need to enable this in special situations where your users cannot access your servers via their LAN IPs, and you need to proxy them through a hostname (DNS) instead.  The default is `0` (disabled), meaning connect using IP addresses.

Good luck, and sorry I don't know the exact cause of this error in your setup.

**Comment by oMikR0n** [comment]
Thanks a lot for the great answer 
i get those messages in Firebug:
Firefox can’t establish a connection to the server at wss://xxx.xxx.56.111:43013/socket.io/?EIO=3&transport=websocket.

I tried both values in server_comm_use_hostnames and web_socket_use_hostnames
I also tried in base_app_url: localhost, 127.0.0.1, 127.0.1.1, my ip, my hostnames.
Tried a lot of port values.
Disabled Firewall. 
Please let me know how i can add route. 
I am on dedicated debian 8

**Comment by jhuckaby** [comment]
Hmm, well it sure sounds like a firewall problem, but I see you've disabled that.  Maybe try running the service on a more common port like 80?

I have no idea how you can add a route, sorry.  I was just saying that Cronicle needs to be able to establish a connection from your PC to the server using its LAN IP, so you need to be in proximity of the server, or have a VPN connection to it's network.

Good luck, and sorry!  This is totally pre-release beta software, so there are indeed bugs.  I've honestly never tried Debian, so there could be some weird Node.js issue on that OS.

Apologies, and good luck to you.  I will leave this issue open in case anyone else has a similar issue and has any clues to help us.

**Comment by oMikR0n** [comment]
Thanks a lot @jhuckaby!
