### ISSUE TITLE
no password  for send mail

### ISSUE THREAD

**Issue by MingqingLi** [jhuckaby/Cronicle#17]
Hello:
      Thank you very much for writing Cronicle.
      But, Why do I have no password parameters for sending mail? Anonymity is sometimes unfriendly.

**Comment by jhuckaby** [comment]
Fixed in v0.6.12, thanks!

### mail_options

Set specific mailer options, such as SMTP SSL and authentication, passed directly to [pixl-mail](https://www.npmjs.com/package/pixl-mail#smtp-options) (and then to [nodemailer-smtp-transport](https://www.npmjs.com/package/nodemailer-smtp-transport#usage)).  Example:

```js
"mail_options": {
	'secure', true,
	'auth', { user: 'fsmith', pass: '12345' },
	connectionTimeout: 10000, // milliseconds
	greetingTimeout: 10000, // milliseconds
	socketTimeout: 10000 // milliseconds
}
```
