### ISSUE TITLE
How to get stdout and stderr output from Python process to show on Live Job log

### ISSUE THREAD

**Issue by jetacpp** [jhuckaby/Cronicle#179]
Hello, I tried many things but basically if I call nodejs file and it contains console.log("blah") then the output will be logged and shown on the web live log. But if I call python file and it contains print("blah") and even os.stderr.write("err"), there is no live log at all.
I tested this with custom plugins, one named testing.js and one testing.py
Could you please show me how to get console output from python process to work with Cronicle.
Thanks !

Edit: I also tried running C program, but the console output was not shown on the live log.

**Comment by robinsonjj** [comment]
Hey, this is what I use:

```python
import logging
import sys
import json

def initialise_stdout_logging():
  root = logging.getLogger()
  root.setLevel(logging.INFO)

  handler = logging.StreamHandler(sys.stdout)
  handler.setLevel(logging.INFO)
  formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
  handler.setFormatter(formatter)
  root.addHandler(handler)

def cronicle_success():
  return json.dumps(dict(complete=1, code=0))

def cronicle_progress(progress):
  return json.dumps({"progress": progress})
```

After you've called the initialise_stdout_logging function you you can use the logging module to print to the log.

**Comment by jhuckaby** [comment]
Calling Python directly from a Plugin should work just fine.  I am not sure why it isn't.  It may have to do with setting the STDOUT / STDERR pipes to "autoflush" so they print after each call.  I had to do this for both the Perl and PHP example Plugins.  Perhaps using a shell enables this automatically, which is why that worked for you?

> But if I call python file and it contains print("blah") and even os.stderr.write("err"), there is no live log at all.

I think you need to add a EOL (line ending character) on those calls, or else they won't be picked up properly by the Cronicle pipe reader.  It reads line by line.  Try `print("blah\n")` and/or `os.stderr.write("err\n")`.

**Comment by jetacpp** [comment]
Thanks @jhuckaby for pointing out to the right directions. I have concluded that for python, print("blah") statement needs to be followed by sys.stdout.flush(). And for C statement printf("blah") needs to be followed by fflush(stdout) for cronicle live log to pickup the console output.

**Comment by Kelesal** [comment]
Hi, all!
So I used `sys.stdout.flush()` and it didn't work. Just get `Log Watcher: Server Connect Error: Error: websocket error (https://IP:443)` every second and then full result of Python script in log.
