### ISSUE TITLE
[Question] - How to run all failed recent jobs?

### ISSUE THREAD

**Issue by leonardorifeli** [jhuckaby/Cronicle#201]
# Reason

My Cronicle is responsible to run ~7k scheduled events for run a HTTP request. But, all request returning an error in the last day, and, all events failed'd.

And, in a 'simple' way I need to force the execution of all scheduled events. Without having to run event by event.

It's possible?

Tks.

**Comment by jhuckaby** [comment]
Yeah, that's way too many separate events for Cronicle, especially if you need to have it fail **all** of them on the first error occurrence in **any** of them.  My recommendation is to use the [Shell Plugin](https://github.com/jhuckaby/Cronicle#built-in-shell-plugin) and run your HTTP requests using a command-line utility like `curl`.  This way you can have the entire job fail on the first error by appending `|| exit 1;` to each line.  Example:

```sh
#!/bin/bash

curl -v http://myserver.com/uri/path/1 || exit 1;
curl -v http://myserver.com/uri/path/2 || exit 1;
curl -v http://myserver.com/uri/path/3 || exit 1;

# many more here...

curl -v http://myserver.com/uri/path/6998 || exit 1;
curl -v http://myserver.com/uri/path/6999 || exit 1;
curl -v http://myserver.com/uri/path/7000 || exit 1;

# success!
exit 0;
```

This way, if any of the `curl` commands fail, the entire job will be aborted, due to the `|| exit 1;` thing.  The `curl` command also supports a wide variety of options, so you can send custom HTTP headers, POST payloads, set timeouts, redirect the output to `/dev/null` if you don't want to see it, etc.  

Good luck!

**Comment by leonardorifeli** [comment]
Tks!
