### ISSUE TITLE
Upgrade uninstalls couchbase

### ISSUE THREAD

**Issue by pakomp** [jhuckaby/Cronicle#232]
## Summary

When running /opt/cronicle/bin/control.sh upgrade the server fails to restart with this crash.log error
Error: Cannot find module 'couchbase'

## Steps to reproduce the problem

Setup cronicle to use the Couchbase storage engine 

Before upgrade couchbase module is installed
npm list couchbase
Cronicle@0.8.28 /opt/cronicle
└── couchbase@2.6.3

Then upgrade to a new version using /opt/cronicle/bin/control.sh upgrade

After the upgrade the couchbase module is missing
npm list couchbase
Cronicle@0.8.32 /opt/cronicle
└── (empty)

So I need to reinstall it using
npm install couchbase
before I can start cronicle again

### Operating system and version?

Debian 9.11

### Node.js version?

v10.16.3

### Cronicle software version?
0.8.28-0.8.32

### Are you using a multi-server setup, or just a single server?
Multi-server setup
### Are you using the filesystem as back-end storage, or S3/Couchbase?
Couchbase
### Can you reproduce the crash consistently?
Yes
## Log Excerpts

Error: Cannot find module 'couchbase'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/cronicle/node_modules/pixl-server-storage/engines/Couchbase.js:10:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by jhuckaby** [comment]
Ugh, I'm very sorry about this.  It's actually `npm` that is uninstalling couchbase, because it isn't explicitly listed as a dependency in the Cronicle `package.json` file.  What a stupid thing.  I am disappointed in them.

I will try to figure something out for the next release, although I am not sure what yet.

**Comment by fullmoon4465** [comment]
I'm using 0.8.31 and I see it listed fyi in the package.json depends

        "dependencies": {
                "async": "2.6.0",
                "bcrypt-node": "0.1.0",
                "chart.js": "2.7.1",
                **"couchbase": "^2.6.8",**
                "font-awesome": "4.7.0",
                "glob": "5.0.15",
                "jquery": "3.3.1",
                "jstimezonedetect": "1.0.6",
                "mdi": "1.9.33",
                "mkdirp": "0.5.1",
                "moment": "2.22.1",
                "moment-timezone": "0.5.14",
                "netmask": "1.0.6",
                "node-gyp": "^6.0.0",
                "pixl-args": "^1.0.3",
                "pixl-class": "^1.0.2",
                "pixl-cli": "^1.0.8",
                "pixl-config": "^1.0.5",
                "pixl-json-stream": "^1.0.6",
                "pixl-logger": "^1.0.14",
                "pixl-mail": "^1.0.8",
                "pixl-perf": "^1.0.5",
                "pixl-request": "^1.0.21",
                "pixl-server": "^1.0.16",
                "pixl-server-api": "^1.0.1",
                "pixl-server-storage": "^2.0.10",
                "pixl-server-user": "^1.0.9",
                "pixl-server-web": "^1.1.7",
                "pixl-tools": "^1.0.23",
                "pixl-webapp": "^1.0.17",
                "shell-quote": "1.6.1",
                "socket.io": "1.7.3",
                "socket.io-client": "1.7.3",
                "uglify-js": "2.8.22",
                "uncatch": "^1.0.0",
                "zxcvbn": "3.5.0"
        },

**Comment by jhuckaby** [comment]
That's probably because `npm` added it to your local `package.json` file when you manually installed it.  But when you upgraded Cronicle, it replaces **all** files, including `package.json`, with a pristine copy from GitHub.  And the base version doesn't have couchbase listed as a dependency.

I can't just add couchbase to the base version, because it is a complicated and binary (compiled C++) library that fails on many OSes and Node versions, and hardly anyone uses it.

I'm working on a fix, but I don't know when it will be ready.

**Comment by fullmoon4465** [comment]
Sweet. No Biggy just noticed the issue when submitting a new one. Yeah this is the first app i actually had to figure out what "couchbase" was but its pretty simple to install a cluster anyway and create its own bucket for this APP to be in HA. I only know about nodejs and npm cause i've been working with NodeRed for a while now; pretty neat

**Comment by jhuckaby** [comment]
This is now fixed in v0.8.34, but please note that any current installs of Cronicle will still wipe out the couchbase module one more time, when they are upgraded next.  It'll only be fixed from after the next upgrade onward, because the installer script itself needs to be updated.  So the next time you upgrade, you'll have to type `npm install couchbase` by hand.

I'm very sorry about all this.  The [npm](https://www.npmjs.com/) command-line utility was changed to completely delete packages that were installed by hand, when a generic `npm update` command is issued (which the Cronicle upgrade script runs to update its own dependencies).  What a mess!

Thanks for reporting this!
