### ISSUE TITLE
feature: Plugins to support Warning status

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/Cronicle#285]
Custom plugin can only report success and error. Would be really nice to have an option to report warning. It could have same style/design as when you do not populate completion code:
![image](https://user-images.githubusercontent.com/31977106/82468684-1adf5200-9a91-11ea-9b4b-91de8a0b4dcb.png)

**Comment by sergioccrr** [comment]
I have been testing Cronicle for 3 months and I am very happy with it, but just this is something I miss.

I hope @jhuckaby can implement it. In any case, great work!

**Comment by mikeTWC1984** [comment]
Implemented this in my fork: https://github.com/mikeTWC1984/Cronicle-X

**Comment by jhuckaby** [comment]
Awesome work, @mikeTWC1984!  Your fork looks amazing -- you've obviously put quite a lot of work into it.  I apologize for being so slow on adding new features, but I've been working on Cronicle v2.0 in stealth mode, which is a ground-up rewrite, and really haven't had time for enhancements on the current version.  Thank you for all your hard work!

**Comment by mikeTWC1984** [comment]
@jhuckaby  Thanks :) The actual changes are pretty small, so shouldn't be a problem to port to v2.0 when it's ready. Wondering -  what are your feelings about when the next version will be ready and is it about promises/async/await/types?  I think as long as there is  a strong core product, many features could be added by community.

**Comment by jhuckaby** [comment]
@mikeTWC1984 I am shooting for a late 2020 release, but I can't promise anything.  This is just a nights & weekends hobby project, really.  I will try to incorporate all of your features in v2, but note that this really is a **complete** ground-up rewrite.  Actually, it's not even called Cronicle anymore!  So I guess it's more of a new product with similar features (and a bunch of new ones).

Nope, it's not about promises/async/await/types.  I am not really into those things (I'm an old-school JS dev).  Someday my job will probably drag me into them, kicking and screaming, but I'm holding off as long as I can 😊 .  The rewrite is more because Cronicle was first written back in 2015, and I've learned a lot since then, and wanted to start fresh with a new core design.  It'll still be a job scheduler of course, but it will also have remote server monitoring, remote terminal (shell), complex multi-job branch control (a redesign of chaining), much better graphs and charts, a fully documented API including all the admin calls, ACID transactions in the storage layer for safe rollback in case of crash or power loss, a fresh look & feel, etc.  Oh, and also it'll ship as a compiled binary executable (via [pkg](https://www.npmjs.com/package/pkg)) so people don't have to install Node.js.

Yikes, now that I look at that feature list, and what I've implemented so far (about half of it), maybe late 2020 is a bit... optimistic.  But we'll see!  😉

**Comment by mikeTWC1984** [comment]
Sounds great. I'm excited to see all these changes. Based on current pace end of 2020 sounds too optimistic indeed ), but probably you can start releasing early alphas step by step around this time. Maybe you should also open github sponsors account to speed it up a bit (like get some funds to hire freelancers or something)
