### ISSUE TITLE
Cronicle crash after a week

### ISSUE THREAD

**Issue by oMikR0n** [jhuckaby/Cronicle#30]
### Operating system and version?
Debian GNU/Linux 8.8 (jessie)

### Node.js version?
v7.10.0

### Cronicle software version?
0.6.15 

### Are you using a multi-server setup, or just a single server?
Single Server

### Are you using the filesystem as back-end storage, or S3/Couchbase?
No

### Can you reproduce the crash consistently?
Nope! It crash after a week or 2

## Log Excerpts

Sun Jun 04 2017 17:19:00 GMT+0200 (CEST)
TypeError: Cannot read property 'title' of undefined
    at /opt/cronicle/lib/scheduler.js:277:61
    at /opt/cronicle/lib/job.js:70:13
    at /opt/cronicle/node_modules/async/lib/async.js:726:13
    at /opt/cronicle/node_modules/async/lib/async.js:52:16
    at /opt/cronicle/node_modules/async/lib/async.js:269:32
    at /opt/cronicle/node_modules/async/lib/async.js:44:16
    at /opt/cronicle/node_modules/async/lib/async.js:723:17
    at /opt/cronicle/node_modules/async/lib/async.js:167:37
    at /opt/cronicle/lib/job.js:54:6
    at /opt/cronicle/node_modules/pixl-server-storage/list.js:775:6

**Comment by jhuckaby** [comment]
This should be all fixed in v0.6.16:
https://github.com/jhuckaby/Cronicle/releases/v0.6.16

Thanks for the bug report!

**Comment by jhuckaby** [comment]
Please note that you were actually getting a legitimate error -- Cronicle was just crashing trying to report it (and that bug is fixed).  From your stack trace, it looks like you were using the "Chain Reaction" feature to launch a second event when the first job completes.  This is fine, however, in your case Cronicle was trying to fail out with this error:

```js
return callback( new Error("Maximum of "+event.max_children+" "+Tools.pluralize("job", event.max_children)+" already running for event: " + event.title) );
```

So it looks like you may have set your "Concurrency" set on your chained event to only allow a certain number of simultaneous jobs, and this limit was going to be exceeded, so the chain reaction launch was aborted.  It looks like this specific situation is only occuring on your environment once every 1 - 2 weeks.

It may be that your chained event got stuck, and was simply still running from last time, due to some unrelated issue.

Hope this helps!

**Comment by oMikR0n** [comment]
I upgraded it and it looks OK now! I also cleared the chained events. I ll come back to report any issues after some days

**Comment by oMikR0n** [comment]
Thanks a lot @jhuckaby! Cronicle is still up and running and all jobs are completing successfully now...
