### ISSUE TITLE
[question]  web server - how to add route to custom html (and keep session)

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/Cronicle#315]
I know you can add static html files to htdocs to serve static content. Problem - I'd like to use ajax to pull some data from cronicle api to display on that page. But those static pages are outside of user session context, so I have to specify api key in ajax url to make it work. Is there a trivial way to add routes to custom pages within user session?

**Comment by jhuckaby** [comment]
The user session ID is stored in the browser `localStorage` system on the client-side, using the key `session_id`.  Your static pages should have access to this.

```js
var session_id = localStorage.session_id
```

Then add that to your AJAX API calls as a query string parameter: `&session_id=HERE`

**Comment by mikeTWC1984** [comment]
OK, cool, that worked.
One more item - do you have a list of events for web sockets? Does it require auth, looks like I can connect without specifying session id
``` 
var socket = io.connect('http://localhost:3012')
 socket.connected // --> true
```

**Comment by jhuckaby** [comment]
I'm so sorry, but none of that stuff is documented anywhere.  It's not designed to be user serviceable, as it's all internal plumbing used by the application.

You can connect, yes, but you can't do anything with the web socket without sending an authentication packet.  I apologize, but I just don't have the time to document that "API", because it is for internal use only.

All I can do, I'm afraid, is point you to the code, so you can see how the Cronicle Web UI does it.  Check here:

https://github.com/jhuckaby/Cronicle/blob/master/htdocs/js/app.js#L163

Good luck, and sorry.

**Comment by mikeTWC1984** [comment]
OK, adding socket.emit( 'authenticate', { token: localStorage.session_id} ) made it work, thanks! Just exploring how it UI gets updated in order to create custom components.
