### ISSUE TITLE
Cronicle deployment failure!

### ISSUE THREAD

**Issue by Eddy1210** [jhuckaby/Cronicle#35]
Hello ,@jhuckaby
install is success, but visits a page is blank！！

I used the ngixn proxy，but
Chrome:

WebSocket connection to 'ws://192.168.1.179:3012/socket.io/?EIO=3&transport=websocket' failed: WebSocket is closed before the connection is established.

How can I only listen on IPV4 ports?

**Comment by andersonb** [comment]
Same here

**Comment by jhuckaby** [comment]
Cronicle requires that you have a network route from your local browser to your individual servers, via their LAN IPs.  If you have a setup which prevents this, you may need to look into these two configuration options: [server_comm_use_hostnames](https://github.com/jhuckaby/Cronicle#server_comm_use_hostnames) and [web_socket_use_hostnames](https://github.com/jhuckaby/Cronicle#web_socket_use_hostnames).

### server_comm_use_hostnames

Setting this parameter to `1` will force the Cronicle servers to connect to each other using hostnames rather than LAN IP addresses.  This is mainly for special situations where your local server IP addresses may change, and you would prefer to rely on DNS instead.  The default is `0` (disabled), meaning connect using IP addresses.

### web_socket_use_hostnames

Setting this parameter to `1` will force Cronicle's Web UI to connect to the back-end servers using their hostnames rather than IP addresses.  This includes both AJAX API calls and Websocket streams.  You should only need to enable this in special situations where your users cannot access your servers via their LAN IPs, and you need to proxy them through a hostname (DNS) instead.  The default is `0` (disabled), meaning connect using IP addresses.

Also, please keep these [Ops Notes](https://github.com/jhuckaby/Cronicle#ops-notes) in mind, as they may pertain directly to you:

- The master server will also open TCP [WebSocket](https://en.wikipedia.org/wiki/WebSocket) connections to each slave on the web server port.
- Each server in the cluster needs to have a fully-qualified hostname that resolves in DNS.
- All servers need to have unique hostnames (very bad things will happen otherwise).
- All servers need to have at least one active IPv4 interface.
- For the "live log" feature in the UI to work, the user needs a network route to the server running the job, via its hostname.
- If you have to change any server IP addresses, they'll have to be removed and re-added to the cluster.
- All servers should have the same exact configuration file (`/opt/cronicle/conf/config.json`).
- All servers need to have correct clocks (timezones do not matter, clock sync does).
- The server hostnames determine priority of which server becomes master (alphabetical sort).

**Comment by HamiltonWang** [comment]
web_socket_use_hostnames: Using hostname causes some problems. The hostname is shared by many application inside the machine, so it may affect other application. I would suggest using base_app_url or having a new field. Thanks

**Comment by HamiltonWang** [comment]
I see what you mean. Cronicle works perfectly in LAN environment. We are having some trouble because we tried to deploy to cloud, so problem arises. So it depends on if Cronicle will stay as a LAN application(which is safer in turn of security and won’t complicate things), or it is also a WAN application.
