### ISSUE TITLE
Endless waiting for Master Server after import backup on new server

### ISSUE THREAD

**Issue by meteoDaniel** [jhuckaby/Cronicle#399]
I have followed the instruction of how to export data from cronicle: 
```
sudo /opt/cronicle/bin/control.sh export /home/mi_master/cronicle-data-backup.txt --verbose
```

I moved this file from one server to another and used the following command to import the backup to the new server:
```
bin/control.sh import /home/mi_master/cronicle-data-backup.txt
```
Now I am in an endless loop of waiting for Master Server. Thanks a lot for help. 

PS: I thought I could use the migration tool but there is no documentation of how to do it between two local file systems on different server.

**Comment by jhuckaby** [comment]
So, that command does a full export including things like information on the server cluster itself (server hostnames, IPs, and server group associations).  This is because the export / import is really designed to backup and restore **to the same server cluster**.  It isn't really designed to copy data between different servers, especially with different hostnames.

What is likely happening here is that when you imported the data to your new server, the hostname no longer matches, so the system cannot figure out that the server should become master.

The data export file is plain text, and you can edit it and even change it before re-importing.  The sections you want to look at are `global/servers/0` and `global/server_groups/0`.  Here is an example of the first:

```
global/servers/0 - {"type":"list_page","items":[{"hostname":"joe16.local","ip":"10.1.10.18"}]}
```

This lists all the servers in the cluster.  If you are exporting and importing data to a new server, you will need to change the hostname and IP of this line in the data file to the NEW server hostname and IP.  Repeat for additional servers in a multi-server cluster, if applicable.

Furthermore, the `global/server_groups/0` line is also very important:

```
global/server_groups/0 - {"type":"list_page","items":[{"title":"Databases","regexp":"(i|q|s)db\\d+\\.|joepro","master":0,"id":"c33ff006"},{"title":"All Servers","regexp":".+","master":0,"id":"4eb85edd"},{"id":"all","title":"Main Group","regexp":"joeretina|joe13|joedark|joe16","master":1}]}
```

This line contains all the information about server groups.  Specifically and importantly, which servers can themselves become master servers.  You will need to make sure that your new master server hostname matches the regular expression defined as the `master` group.

Alternatively, you can first setup your new server / cluster using the setup script, and then do a "selective" export / import from your old server that **excludes** the server names and server groups.  You can just grep those things out of the export data file like this:

```
cat /home/mi_master/cronicle-data-backup.txt | grep -v global/server > /home/mi_master/cronicle-data-backup-2.txt
```

This would create a copy of the export data named `cronicle-data-backup-2.txt` which would exclude the servers and server groups.  The idea here would be to import this onto a new server that was already setup using the setup script, so the initial servers and server groups would be auto-created, and not clobbered by the import.

Hope this helps.  Good luck!

**Comment by meteoDaniel** [comment]
Thanks a lot for this support :)

**Comment by sdesalas** [comment]
For anyone else tying to backup to a new server, I found this works a bit better:

```
cat /home/mi_master/cronicle-data-backup.txt | grep -v -e "^global/server" > /home/mi_master/cronicle-data-backup-$(date +%a).txt
```

For the following 2 reasons:

1. Using `grep -v -e "^global/server"` means that it only picks up lines `that start with "global/server"` so your backup script wont miss the schedules if for some reason they include  the string "global/server" in them (this happened to me).
2. Using `cronicle-data-backup-$(date +%a).txt` means that you get a free 7 day backup rotation (using the day of the week ie `cronicle-data-backup-Fri.txt`).
