### ISSUE TITLE
Suggestion: prefix ("root") for storage backend?

### ISSUE THREAD

**Issue by aldanor** [jhuckaby/Cronicle#40]
It would be nice if it was possible to specify a root for Cronicle to store all its data in, so that `global/server_groups` could be for example `my_cronicle_folder/global/server_groups`.

This would help greatly, for example, if you have to use a shared S3 bucket (or DigitalOcean Space) for some reason.

**Comment by aldanor** [comment]
(Not sure if this would be a better suggestion for `pixl-server-storage` repo though)

**Comment by jhuckaby** [comment]
Thanks for the suggestion!  You can already do this with the [Filesystem](https://github.com/jhuckaby/Cronicle#filesystem) backend, by setting the `base_dir ` property.  However, I will add this to the TODO list for the [S3](https://github.com/jhuckaby/Cronicle#amazon-s3) and [Couchbase](https://github.com/jhuckaby/Cronicle#couchbase) backends.

**Comment by aldanor** [comment]
Thanks!

(Just to clarify the real use case: Digital Ocean happens to price each bucket separately, so you would currently have to pay them to avoid name clashes in the bucket).

**Comment by aldanor** [comment]
Just ran into a collision into something else today due to Cronicle storing logs in '/logs' in S3's bucket root :( Wondering if prefix support could be possibly added to S3, or is there any way to help?

Thanks!

**Comment by jhuckaby** [comment]
Yikes!  I'm very sorry this happened to you, @aldanor.  I have just released [pixl-server-storage v1.0.8](https://github.com/jhuckaby/pixl-server-storage/releases/tag/v1.0.8), which has support for a new `keyPrefix` property in both the S3 and Couchbase engines.  [Cronicle docs](https://github.com/jhuckaby/Cronicle#amazon-s3) have been updated.

However, since you already have a Cronicle installation with S3 setup and running, this will take some additional work.  I will write instructions on how to migrate your critical data, but this doesn't include all your job history, activity and logs.  If you cannot afford to lose those, you'll have to find a way to "move" them into a subfolder in your S3 bucket.  You might have some luck with an app such as [Transmit](https://panic.com/transmit/) which has very good S3 support (if you use a Mac).

Anyway, here are the steps, which will preserve and move your critical Cronicle data (i.e. users, API keys, schedule, plugins, servers, server groups, and categories).  Basically, we'll be using the [Data Import and Export](https://github.com/jhuckaby/Cronicle#data-import-and-export) feature to export and import your data.  This assumes you want to move everything into a "cronicle" directory in your S3 bucket.

### Stop the Cronicle service on all your servers

```
sudo /opt/cronicle/bin/control.sh stop
```

### Export all critical data from your master server

```
sudo /opt/cronicle/bin/control.sh export /var/tmp/cronicle-data-backup.txt --verbose
```

### Upgrade your pixl-server-storage module to v1.0.8 on all your servers

```
cd /opt/cronicle
sudo npm install pixl-server-storage
```

### Update your S3 configuration on all your servers

```
sudo vi /opt/cronicle/conf/config.json
```

Add the `keyPrefix` property into your `S3` configuration object:

```js
"S3": {
	"keyPrefix": "cronicle",
	"params": {
		"Bucket": "YOUR_S3_BUCKET_ID"
	}
}
```

Make sure you change this on **all** your Cronicle servers.  All the configuration files should be identical.

### Re-import your Cronicle data on your master server

```
sudo /opt/cronicle/bin/control.sh import /var/tmp/cronicle-data-backup.txt
```

This should import everything to S3 using your new `keyPrefix`.

### Restart Cronicle service on all servers

```
sudo /opt/cronicle/bin/control.sh start
```

Wait ~60 seconds for the master server to activate, then load up the UI to make sure all your critical data is still there (i.e. Users, Plugins, Categories, Servers, Server Groups, API Keys and all Scheduled Events).

### S3 Cleanup

This migration process will not automatically "delete" the old Cronicle S3 data, which was scattered on the root of your S3 bucket in various directories.  You will have to go in and manually delete everything, preferably using an app that makes this somewhat easy (such as Transmit).

The top-level directory names Cronicle uses are:

- `_cleanup/`
- `_temp/`
- `global/`
- `jobs/`
- `logs/`
- `sessions/`
- `users/`

However, be careful deleting any directories that may have collided with your other applications.  I believe you said you have an app that uses a top-level `logs` directory.  So you'll have to traverse into that directory to cleanup the Cronicle-specific sub-keys.  Sorry about that 😞 

Good luck, and I hope this helps!

**Comment by aldanor** [comment]
Thanks a million, appreciate the fix and the notes on migration! 

Fingers crossed. I was wondering whether it would be safe to just move all Cronicle related folders to a new prefix directly and not via export/import, or is there any catch? (e.g. `s3cmd mv s3://bucket/_cleanup s3://bucket/prefix/_cleanup`, etc, while the services are stopped)

**Comment by jhuckaby** [comment]
You bet!

To be honest, I've never used `s3cmd mv`.  Does it really do a true "recursive" move of all keys under the specified one?  If so, then this would probably work, and preserve all your data, including history and logs.  It's up to you!  🤞 

There's no catch, other than the directories have to arrive at the new prefixed location exactly as specified, with the exact matching `keyPrefix`, which is case-sensitive.  Cronicle doesn't use any S3 APIs except for `putObject` and `getObject`.

**Comment by jhuckaby** [comment]
I'd recommend that you still do the export command, just in case `s3cmd` messes something up.  This way you'll have a backup of everything critical, and can get back to a good state (sans history and logs of course).

**Comment by aldanor** [comment]
Whew, everything seems fine after `s3cmd mv`'ing everything to a new prefix. Thanks again for help!

**Comment by jhuckaby** [comment]
Whew indeed!  Thanks for the feature request!
