### ISSUE TITLE
Minor suggestion: a button to remove event result from the history

### ISSUE THREAD

**Issue by aldanor** [jhuckaby/Cronicle#41]
Apologies in advance for keeping spamming with suggestions, but here's another small one :)

One thing I've realized would be nice to have is a simple option to manually clear results from history. It's currently possible to delete events but not their results. E.g., when playing around with Cronicle to see what works and what doesn't, especially when it comes to more complicated things like web hooks, chain reaction and API - would be great if those runs could be cleared manually from the history, so it's not littered with temporary stuff?

Could probably be located next to 'Run Again' button in 'Completed Job Details' (speaking of this button, by the way, it seems to overlay the underlying table text on small-to-medium sized screens, is that intentional?). 

(Could also potentially ask the user whether to clear the event history when deleting the event.)

Thanks!

**Comment by jhuckaby** [comment]
No need to apologize for feature requests.  This one has actually been on my TODO list forever.  It's just a bit tricky to implement due to the way the history "[lists](https://github.com/jhuckaby/pixl-server-storage#lists)" are represented in storage.  It's currently non-trivial to splice items out of the middle of a huge list -- I have an [API](https://github.com/jhuckaby/pixl-server-storage#splicing-lists) for it, but it's just slow -- too slow, for example, if using S3 backend with a 10K history list.  I'll take a fresh look at how to do this properly tho, thanks!

**Comment by jhuckaby** [comment]
The "Run Again" button overlaying the text is just a cosmetic bug in the CSS.  I'll work on that too.

**Comment by aldanor** [comment]
> but it's just slow -- too slow, for example, if using S3 backend with a 10K history list

I see, that makes total sense. Skimming through pixl-server-storage docs, the list on S3 is stored sort of like deque is implemented in C++ if I understand correctly? (i.e. chunked/paged storage)

Here's one random thought/hack: you could mark the list item as 'expired' and ignore it for all purposes; then actually kill it later, during the daily maintenance/cleanup. This would probably require quite a lot of filtering throughout the code though...

**Comment by aldanor** [comment]
> Here's one random thought/hack: you could mark the list item as 'expired' and ignore it for all purposes; then actually kill it later, during the daily maintenance/cleanup

However, one can always pretend it's a cool needed feature, e.g. it allows you to cheaply implement an "Undo" button when deleting event log :)

**Comment by jhuckaby** [comment]
> the list on S3 is stored sort of like deque is implemented in C++ if I understand correctly? (i.e. chunked/paged storage)

Yup, I think that is correct.  I don't remember exactly how a C++ deque worked, but this is definitely a sort of hybrid chunked / linked list, but you can also randomly access pages, for super-fast gets.

> you could mark the list item as 'expired' and ignore it for all purposes; then actually kill it later, during the daily maintenance/cleanup

Yup, I thought of that, but unfortunately it starts getting hairy pretty quick, because the UI displays a "paginated" table, so if some items are "deleted" and not shown, it will totally mess up the paging algorithm.  A user could "delete" all the items on the first page, for example, and it would be blank.  I was thinking of either marking the item as deleted and showing a "ghost" in the UI, like a whole table row with a grayed out "(Deleted)" label, which would then be cleaned up at nightly maint, OR just biting the bullet and rewriting my listSplice() function to be more efficient.

I'm not sure how to delete an event's entire job history when the event is deleted.  The system would be faced with the prospect of removing potentially tens of thousands of items out of the history list, intermixed with thousands of other events.  Even during nightly maintenance, I am not sure how to implement this.  It might have to wait for 2.0, where I am planning on using a more traditional database "table" like structure.

**Comment by aldanor** [comment]
> so if some items are "deleted" and not shown, it will totally mess up the paging algorithm

Hmm... that is, unless you store indices to the deleted items somewhere separate. This list will most always be empty, or near empty. E.g. if your page size is 5, and deleted entries are `[0, 4, 9]`, then before deletion your first three pages are `[0, 4], [5, 9], [10, 14]` and after deletion they are `[0, 6], [7, 12], [13, 17]` (both boundaries inclusive). Here, for instance, `7 = 5 + (0 <= 5) + (4 <= 5) + (9 <= 5)`.

**Comment by jhuckaby** [comment]
Clever idea, but extreme cases would break it.  Imagine 10,000 items in the job history, and 9,999 are all for event A, and 1 for event B.  Then you delete event A from the schedule, and we "delete" the 9,999 items, leaving 1 "real" item for event B.  Then someone goes to view the history page.  The storage actions required to render that first history page would require searching through hundreds of pages to "eliminate" the 9,999 deleted items, and only show the 1 elusive remaining item, like finding a needle in a haystack.  If the user was also using Amazon S3 backend, for example, this equates to 100+ S3 gets for a single API call, and would probably hang the UI for 10 seconds.  I understand this is an extreme example, but I have to design with this in mind.

I've been toying with the idea of removing the pagination altogether, and instead just show a "stream" of matching history items, which auto-appends as you scroll to the bottom, kind of like how Facebook/Twitter do it.  This would allow me to have a "sparsely populated" list with deleted items in the middle, and not really have to worry about pagination.  That extreme case of 9,999 deleted items with 1 real item would still hurt, however.

**Comment by aldanor** [comment]
Agreed, this is tough... :)

Your example would work, I guess, if the 'deleted_items' list was just a single JSON object, inside a single file / S3 object. If non-existent, let's say it's assumed to be empty for backwards compat. In your extreme example, it would be a ~48K file; comparing an array 10k ints to a constant is still a matter milliseconds in node. I'm not 100% sure whether that's something feasible, how it affects atomicity, etc -- just trying to bounce off some ideas :)

**Comment by jhuckaby** [comment]
Yup, I see what you're saying.  This may be possible, but I'll have to ponder, as it affects a ton of code, as you said.

**Comment by jhuckaby** [comment]
Initial implementation of this is in [v0.7.5](https://github.com/jhuckaby/Cronicle/releases/tag/v0.7.5), but it still needs a lot of work.  Leaving this issue open.
