### ISSUE TITLE
Persist execution time as variable in plugin, possible?

### ISSUE THREAD

**Issue by meteoDaniel** [jhuckaby/Cronicle#439]
### Discussed in https://github.com/jhuckaby/Cronicle/discussions/436

<div type='discussions-op-text'>

<sup>Originally posted by **meteoDaniel** July 27, 2021</sup>
We are using cronicle to run e.g. python scripts in docker containers. These python scripts require a fixed timestamp according to the execution time. 
E.g.: we have execution time 06:00 , we need this as a parameter because in case of a retry it is difficult to obtain the origin execution time of the task. It is the cause of using a `DATE` variable defined within the shell script plugin:
```
DATE=$(date -d -u +"%Y-%m-%dT06:00:00+00:00")
``` 

So is there a way to have the execution time as variable (e.g. env variable in shell script) ?  Or do you have other solutions to persist the execution time?

@jhuckaby </div>

**Comment by mikeTWC1984** [comment]
Possible "built-in" workaround:
1) Instead of retry - chain job to itself (on error)
2) Wrap your current script in try/catch block
3) Check "interpret JSON" and print a json like below in the catch block
  '{ "chain_data": { "custom_key": "foobar", "value": 42 } }'
4) In the begging of the script capture sys.stdin which would be json string and parse it. It will contain above json from previous job (under chain_data property)

In many cases you can just keep "global" state  in the file (like /tmp/myevent )

In general I think it might be handy to keep event "last run details" in that input json. Maybe even collect some stats from previous N executions (like avg duration, success rate, etc)
