### ISSUE TITLE
How to set an event start date and end date?

### ISSUE THREAD

**Issue by gdunn1** [jhuckaby/Cronicle#489]

**Comment by gdunn1** [comment]
Has anyone come up with a method to handle an event that has to be scheduled at a specific future start date and end at a certain date?

**Comment by jhuckaby** [comment]
Alas, Cronicle v1 doesn't support this feature, but the next major release (Cronicle v2 a.k.a Orchestra) indeed has it already built-in.  Orchestra will be released later this year (2022).

**Comment by gdunn1** [comment]
Thank you for the quick response. We can't wait until the end of year any suggested workarounds in the mean time without creating a lot of extra work?
Gideon
________________________________

**Comment by jhuckaby** [comment]
Yeah, there is a workaround, but it's a bit complicated.  I will spend some time writing it up as a Wiki article when I get a chance.  In short, you can use the REST API and the HTTP Request Plugin to enable/disable the target event at certain dates/times.  Basically, use 3 different events.  Your main event which runs your job, a separate event to enable it at a future date/time, and a 3rd event to disable it at a future date/time.

- REST API: https://github.com/jhuckaby/Cronicle#json-rest-api
- update_event call: https://github.com/jhuckaby/Cronicle#update_event
- HTTP Request Plugin: https://github.com/jhuckaby/Cronicle#built-in-http-request-plugin

**Comment by gdunn1** [comment]
Appreciate the help and the article you are creating,

**Comment by mikeTWC1984** [comment]
@gdunn1  Btw, if you use shell plugin you can also print json message with update_event key to enable/disable event or change other event options (without REST api). E.g. to disable event upon completion put something like this at the end of your script:
```bash
# add some if/else logic for end time here
echo '{"update_event": {"enabled": 0}}'
```
Also, make sure to check "Interpret JSON" flag in event properties.

here is link to docs about this:
https://github.com/jhuckaby/Cronicle#updating-the-event

To start it initially create some other event with custom schedule (for exact date/time) that would chain you target event

**Comment by gdunn1** [comment]
@mikeTWC1984 thank you for your input. My next question was how to set up one event to call another which you indicated. @jhuckaby when do you think a working example in your write up/article will be available?

**Comment by jhuckaby** [comment]
Here you go: https://github.com/jhuckaby/Cronicle/wiki/Starting-and-or-Ending-Dates-Times-for-Recurring-Events

**Comment by gdunn1** [comment]
@jhuckaby thank you for the article created I will look at it btw when is the next version of Cronicle being released that has this built in functionality? I know you mentioned end of this year any specific month or date?

**Comment by jhuckaby** [comment]
@gdunn1 Apologies, but I don't have a more specific release date.  It will be this year for sure (2022), but that's as granular as I can get at present.  When I get the product closer to release I'll update this issue, update the Cronicle README with news, and tweet from the `@CronicleApp` Twitter account.  I'm also working on a landing page with a signup button for subscribing to updates.

**Comment by gdunn1** [comment]
@jhuckaby Thank you

**Comment by gdunn1** [comment]
Hi Joseph,
I want to find out when the next version of Cronicle is scheduled for release that supports setting up start and end dates for events? I believe this will be offered in the Orchestra release before the end of year. If so, when?

**Comment by jhuckaby** [comment]
Sorry for the lack of updates.  Life keeps getting in the way.  I'm just a sole developer working on Orchestra, and I have a day job, so it's difficult to both find time to work on it, and also predict a release date.

I'm spending every free moment I can on Orchestra, and it's coming along nicely.  I'm working on it as I type this, in fact.  However, I still have a ways to go yet.

I really shouldn't make any specific predictions or estimates, because it creates stress for me, and I am trying to do this for fun.

Let me just say, it's progressing!  I'll probably miss my 2022 goal, and I deeply apologize for that, but I am trying my very best.

It'll be here someday soon 😊

**Comment by gdunn1** [comment]
Thank you for the quick response. I completely understand these things take time and life always has unexpected events lol. I was able to code start and end dates using trigger events as suggested. However, the one item that takes a lot of infrastructure to manage is mostly with a single event that has to be ran every 2, 3, 4 or more months since we display history in our apps for when an event ran successfully last and is scheduled to run next. Is this capability for running events every x month(s) supported in an upcoming release or patch before Orchestra is available? If so, when?

**Comment by jhuckaby** [comment]
Well, you can achieve every 2, 3 and 4 months right now, because all three of those numbers divide evenly into 12 (i.e. the number of months in a year).

So every 2 months would look like this:

<img width="638" alt="Screen Shot 2022-11-04 at 11 47 26 AM" src="https://user-images.githubusercontent.com/700765/200052606-0e060cf9-acc0-4af9-8c14-cd186a9edb57.png">

Every 3 months would look like this:

<img width="633" alt="Screen Shot 2022-11-04 at 11 47 58 AM" src="https://user-images.githubusercontent.com/700765/200052636-5c53e073-4e33-4819-a0d2-dea46123196a.png">

And every 4 months would look like this:

<img width="638" alt="Screen Shot 2022-11-04 at 11 48 17 AM" src="https://user-images.githubusercontent.com/700765/200052673-ab3d864e-ba95-4840-a67d-4b9d80e9b62f.png">

5 doesn't divide evenly into 12, alas, but 6 does, so you can also achieve every 6 months like this:

<img width="635" alt="Screen Shot 2022-11-04 at 11 48 31 AM" src="https://user-images.githubusercontent.com/700765/200052692-bfe93294-84bc-4a1f-87d6-7a390f4578fe.png">

Orchestra will allow you to set multiple individual single future dates to run, so that should handle things like every 5 months, and other odd values (i.e. you can just pre-populate it for 10+ years out).

I don't have any plans to backport this feature to Cronicle, sorry.  It's just too much work to implement the whole thing twice.

**Comment by gdunn1** [comment]
If you are doing it from the GUI, you are correct however not programmatically which is how it needs to be done per our services and handling requests from a web application. Our users have no interaction with this Cronicle interface by design.

**Comment by gdunn1** [comment]
So I assume no way programmatically until the next big release comes out corrrect?

**Comment by jhuckaby** [comment]
Errr... what?

Everything you can do in the UI you can do with the API.  Use the [create_event](https://github.com/jhuckaby/Cronicle/blob/master/docs/APIReference.md#create_event) or [update_event](https://github.com/jhuckaby/Cronicle/blob/master/docs/APIReference.md#update_event) calls, and specify a custom timing object:

https://github.com/jhuckaby/Cronicle/blob/master/docs/APIReference.md#event-timing-object

For every 2 months do this:

```json
"timing": {
	"months": [1, 3, 5, 7, 9, 11],
	"days": [1],
	"hours": [0],
	"minutes": [0]
}
```

For every 3 months this:

```json
"timing": {
	"months": [1, 4, 7, 10],
	"days": [1],
	"hours": [0],
	"minutes": [0]
}
```

4 months this:

```json
"timing": {
	"months": [1, 5, 9],
	"days": [1],
	"hours": [0],
	"minutes": [0]
}
```

And so on.  You get the idea.

**Comment by gdunn1** [comment]
it just doesn't work with months 5, 7, 8, 9, 10, 11 if you run a schedules consectutive years

**Comment by gdunn1** [comment]
I knew we had a good reason for creating seperate events to handle this issue within the same year its fine I believe
