### ISSUE TITLE
Long event list become unwieldy

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [jhuckaby/Cronicle#491]
In the meantime we have about 850 events in our eventlist, which become a little bit unwieldy. Is there any chance to get someting like paging oder collapsing categories in the near future? Whould be a great help for us.

Btw: the search is also a bit tricky. I'm usually not able to write a full search string in the field. The Cronicle user interface updates so often that I can't finish my search query.

![image](https://user-images.githubusercontent.com/73586581/165281601-d20c0912-b434-4da2-8c20-1528acefc7f2.png)

**Comment by jhuckaby** [comment]
Your screenshot looks strange... are you using a fork of Cronicle or something?  What is that yellow icon next to the "Scheduled Events" heading?

If you are using the *real* Cronicle, there are menus on the top right corner that can filter by category (and several other things):

<img width="886" alt="Screen Shot 2022-04-26 at 9 58 07 AM" src="https://user-images.githubusercontent.com/700765/165353616-6b1a4e6d-3b84-4d69-aaa1-cae0f4328c3e.png">

Does that help at all?

**Comment by dheise-rheinenergie-trading-com** [comment]
Hi Joseph,

good observation skills ;-) We are currently using the fork cronicle-edge from MikeTWC1984. 

I know the filter options. But they have the same problem as the search box. The UI often refreshes so fast that I am unable to select a category because the dropdown closes before I can select anything. Especially in the lower categories, it takes a little longer to scroll down. We have 86 categories.

Theoretically it would be sufficient if the refresh only applies to the table and the filter options are unaffected.

Daniel

**Comment by mikeTWC1984** [comment]
Yeah, that's because UI gets refreshed on each job start/completion. As a temp solution you may try to disable this, find those line on Schedule.class.js (or in _combo.js if you don't want to rebuild it)
```js
	onStatusUpdate: function (data) {
		// received status update (websocket), update sub-page if needed
		if (data.jobs_changed && (this.args.sub == 'events') && !app.scheduleAsGraph) this.gosub_events(this.args);
	},
```
and comment out  the line starting with "if"

Probably this needs to be configurable, event status on schedule page is not that useful when you have many events.

**Comment by jhuckaby** [comment]
On my TODO list to fix.  Thanks!

**Comment by mikeTWC1984** [comment]
Speaking of collapsible groups - I think it might look natural. Below is a quick sketch 

![image](https://user-images.githubusercontent.com/31977106/165655470-eba36446-3571-4833-a134-8801c4f06239.png)

**Comment by jhuckaby** [comment]
Will do that also, thanks!

**Comment by jhuckaby** [comment]
Alright, so the primary issue here is now fixed in v0.9.4: https://github.com/jhuckaby/Cronicle/releases/tag/v0.9.4 -- specifically, when jobs are updated (started or completed) the menus and search box no longer break.

However, redesigning the main event view with collapsible categories is going to take some additional thought.  That table can be reorganized on-the-fly to group events by categories, plugins, or targets, using these little controls on the top-right:

<img width="83" alt="Screen Shot 2022-04-27 at 9 40 32 PM" src="https://user-images.githubusercontent.com/700765/165677932-2f08750f-a3a7-49a4-81a3-3d2c1da57513.png">

This complicates the problem, because I'm not only dealing with category sections in that table.  I have to think about the other 3 modes.  Also, this is just a UI thing, but I don't have icons for "collapsed" plugins and targets.  That trick only works with folders (i.e. categories).  Also, the state should be saved and restored per user somehow, which will take some doing.  This is just a bit of a can of worms here.

I need to put some more thought to this.  Also, I'm hard at work on Cronicle v2.0 (Orchestra) which has a complete redesign of the event view.  I should really be focusing my efforts there, to make that a highly usable UI, even with hundreds (or possibly thousands) of events.  I'm mainly interested in fixing bugs on Cronicle v0, and possibly adding "low hanging fruit" features.

I'll keep thinking about it.

**Comment by dheise-rheinenergie-trading-com** [comment]
Hey @jhuckaby & @mikeTWC1984 ,
you both are great. thanks for the fix and the ideas at the speed of light.

will test it in the next days, when I'm back in the office.

Daniel

**Comment by mikeTWC1984** [comment]
@jhuckaby I think there is a way to get simple version of collapsible groups without keeping the state - just assign group related class to the data row, and then toggle hide/show on clicking group label.
The only thing missing is an option to hide row on condition while generating table. Can you add this option to getBasicTable function:
https://github.com/jhuckaby/pixl-webapp/blob/master/js/page.js
say if tds.hide is true then set display:none. 

In general I agree it's better to add some place to store UI state. It's a bit annoying when all that filtering disappear  (on schedule page) when you change view.

**Comment by dheise-rheinenergie-trading-com** [comment]
Hi @jhuckaby & @mikeTWC1984,

Today I installed the lastest fork (v1.5.9) from Mike, which also includes the fix from Joseph for the broken filters/searchfield when the pagecontent reloads.

But in my case, it doesn't work: I open the dropdown for category and every time the running job counter in the upper right corner next to the time changes, my dropdown closes.

my browser is chrome v99 - if it matters...

any idea?

**Comment by mikeTWC1984** [comment]
@dheise-rheinenergie-trading-com yeah, chrmomium browsers cache js/cc files. I usually use firefox for dev work. Try to clear cache or run  in incognito tab. I still do some testing, will put release notes later

**Comment by dheise-rheinenergie-trading-com** [comment]
did some additional tests without success:
- chrome with cleared cache in developer mode
- chrome in incognito
- edge 
- edge in incognito

**Comment by mikeTWC1984** [comment]
@dheise-rheinenergie-trading-com  you are right. This is happening because I use update_event api upon job completion to populate last exit code and other info on event, so it changes  the state of the schedule (not  just event state), and this triggers page redraw. Will give it some thought and fix soon

**Comment by dheise-rheinenergie-trading-com** [comment]
Everything works really fine with the latest release! Thanks again to @jhuckaby  for the new column "last run" and @mikeTWC1984  for the collapsing feature!
