### ISSUE TITLE
Upgrade to Version 0.9.7 didn't upgrade socket.io

### ISSUE THREAD

**Issue by aric89** [jhuckaby/Cronicle#501]
## Summary

Upgraded Cronicle to version 0.9.7 but socket.io is still at 1.7.3

Cronicle@0.9.7 /opt/cronicle
└── socket.io@1.7.3  invalid

## Steps to reproduce the problem

Run version 0.9.7 with version socket.io 1.7.3

## Your Setup

One Master server and One Slave server. The Slave server has socket.io 4.4.0 and the Master has 1.7.3

### Operating system and version?

Master is on Oracle Linux 7.9 and Slave is on Fedora 35

### Node.js version?

nodejs 10.23.3-1.0.1.el7

### Cronicle software version?

version 0.9.7

### Are you using a multi-server setup, or just a single server?

Multi-Server setup

### Are you using the filesystem as back-end storage, or S3/Couchbase?

Filesystem

**Comment by jhuckaby** [comment]
I believe your Node.js is too old.  Version v10 is not supported anymore.  I'm guesing socket.io won't upgrade because the new version requires a newer Node.js.

If you can, please upgrade your Node.js to v16 (the current LTS version).

If that doesn't work, try these commands:

```
cd /opt/cronicle/
sudo rm -rf node_modules
sudo npm install
```

Oh, you resolved it while I was typing.  Okay then 😊 

You really should upgrade your Node.js tho.  I'm kind of amazed it even works on Node.js v10.
