### ISSUE TITLE
new npm reported vulns

### ISSUE THREAD

**Issue by mikeTWC1984** [jhuckaby/Cronicle#559]
I wants to update formidable package on pixl-server-web. Upgrading to 2.1.1  (from 2.0.1) seemed to clear this issue

**Comment by jhuckaby** [comment]
Thanks!  I was notified via Snyk about a vuln in qs, but I see now see it was introduced through formidable.

<img width="1192" alt="Screen Shot 2022-12-11 at 9 44 29 AM" src="https://user-images.githubusercontent.com/700765/206919788-a98cdf8d-8b0c-4ade-88da-a63259e1c91f.png">

Strange, I can't v2.1.1 in the [formidable changelog](https://github.com/node-formidable/formidable/blob/master/CHANGELOG.md), but 🤷🏻‍♂️ .

Fixed in pixl-server-web@1.3.15.
