### ISSUE TITLE
Wrong IP selected on AWS servers

### ISSUE THREAD

**Issue by photoplyr** [jhuckaby/Cronicle#58]
## Summary

I installed Cronicle on an was server. it installed and started correctly. But when I access the servers on the public IP address, the main page displays but is blank. After some debugging the browser its trying to connect through the internal IP address

Example:

I connect web browser through http://12.54.223.188:3012

The Browsers show:
WebSocket connection to 'ws://142.31.1.212:3012/socket.io/?EIO=3&transport=websocket' failed: WebSocket is closed before the connection is established.

## Your Setup
Small ubuntu AWS server

### Operating system and version?

Ubuntu t2.micro

### Node.js version?

v6.11.2

### Cronicle software version?

Version 0.8.2

### Are you using a multi-server setup, or just a single server?
Single

### Are you using the filesystem as back-end storage, or S3/Couchbase?
NO

**Comment by jhuckaby** [comment]
Thank you for the bug report.  This is actually *as designed* behavior with the default configuration.  Cronicle is designed specifically to connect to servers via their local LAN IPs.  However, you can easily change this to use the server *hostname* instead.  What you want is to set this configuration directive:

https://github.com/jhuckaby/Cronicle#web_socket_use_hostnames

> Setting this parameter to 1 will force Cronicle's Web UI to connect to the back-end servers using their hostnames rather than IP addresses. This includes both AJAX API calls and Websocket streams. You should only need to enable this in special situations where your users cannot access your servers via their LAN IPs, and you need to proxy them through a hostname (DNS) instead. The default is 0 (disabled), meaning connect using IP addresses.

You actually have two choices here.  You can either change your server's hostname to something that resolves to its public IP address, *or* you can simply copy the server's hostname and paste into a local `/etc/hosts` file on your machine, and remap it locally to the public IP.

Either way, with the `web_socket_use_hostnames ` configuration directive set, Cronicle will connect to the server via the hostname rather than the IP.  Good luck, and sorry for the confusion!
