### ISSUE TITLE
Can't find my original issue

### ISSUE THREAD

**Issue by geofffox** [jhuckaby/Cronicle#619]
The event stats for most of my scripts no longer exists.

## Summary

You had shown me how to fix this years ago but I can't find our thread.  I'd prefer to blow everything out and start again.
Cronicle 0.8.44

CentOS Linux 7 (Core)

**Comment by jhuckaby** [comment]
Hey @geofffox, hope you are doing well!

Yeah, a number of users have reported similar issues.  It should all be fixed in the latest version -- if you blow everything away and start fresh, that should work just fine.  Note that Cronicle now requires Node.js v16+, so make sure you grab that too.  Instructions below.

However, if you decide that you want to fix / repair your current install, I recommend upgrading to the latest version of Cronicle, then following the steps here:

https://github.com/jhuckaby/Cronicle/wiki/Troubleshooting

Specifically, these sections:

## Node.js Version

Make sure you have the latest stable Node.js for Cronicle to run smoothly.  As of 2023 the minimum supported version is v16.  Here are instructions for upgrading your Node.js via package manager:

https://nodejs.org/en/download/package-manager

Or grab a precompiled binary from here:

https://nodejs.org/en/download/releases

Cronicle expects the `node` binary to be in the root user's PATH.

## Cronicle Version

Please make sure you are running the latest version of Cronicle.  Instructions are here:

https://github.com/jhuckaby/Cronicle/blob/master/docs/CommandLine.md#upgrading-cronicle

## Storage Transactions

It is highly recommended that you enable **storage transactions**.  This protects against database corruption for events like backend storage errors, crashes and sudden power loss.  Cronicle ships with transactions enabled in the default config, but if you have an older version you may need to manually enable them.  Add these two properties into the `Storage` object in your `/opt/cronicle/conf/config.json` file:

```js
{
	"Storage": {
		"transactions": true,
		"trans_auto_recover": true,
		
		...
	}
}
```

Make sure Cronicle is fully stopped on all master servers before making this change.

## Storage Repair

If you experience any strange behavior in Cronicle, such as job history not populating, you may have some database corruption.  In this case, a repair script is provided, which will scan the entire database and make any necessary repairs.

To run the repair script, first stop Cronicle on all your master servers:

```sh
sudo /opt/cronicle/bin/control.sh stop
```

Then, run the repair script in "dry run" mode.  This will detect corruption but not make any changes:

```sh
sudo /opt/cronicle/bin/storage-repair.js --dryrun
```

If the script detects any issues in your storage database, the output will include something like:

```
Dry-run complete!
4 repairs are needed.
```

Run the script without the `--dryrun` argument to actually make the repairs:

```sh
sudo /opt/cronicle/bin/storage-repair.js
```

Note that some data loss may occur when repairing storage records.  It is recommended that you always keep backups of your data.

Once everything is repaired, you can restart Cronicle on all your master servers.
