### ISSUE TITLE
cronicle.net is in http only

### ISSUE THREAD

**Issue by mahmut-spark** [jhuckaby/Cronicle#620]
Hi, not sure if this is by design but project website is running http only.

Reporting just in case.

**Comment by tburnshrsd** [comment]
I was just about to report that! Security conscious users are rightfully going to balk at that and question the overall security of the software. It isn't the plain http alone that bothers me, it is the fact that on the front page they have a one liner they are recommending running as root.

Let's Encrypt certs are widely recognized and free. Setting up TLS on Apache HTTPD, Nginx, haproxy, or whatever they are front-ending the site with doesn't take a lot of time.

Considering it has been almost a month since you reported this and haven't even gotten a response, it doesn't bode well, IMO. Especially considering I see they have had some commits since then.

**Comment by jhuckaby** [comment]
Good grief, @tburnshrsd.  It's on my TODO list.  Please understand, this is 100% free and open source software, created by a single dev in his spare time.  Be nice, please.

Cronicle recommends running as root because one of its primary features is to dynamically switch users to run different jobs.  Only root can do that.

**Comment by mahmut-spark** [comment]
@jhuckaby, thank you for your update and thank you for all the work you are putting on cronicle. It is much appreciated. But please also consider @tburnshrsd comments in a constructive manner. Not having an SSL website, and earlier copyrights on the page somewhat shadows the quality of your project.

That being said, perhaps it would be better to switch the project website to github pages. Please let me know if I can be of help in anyway. Thank you again.

**Comment by tburnshrsd** [comment]
"dynamically switch users to run different jobs. Only root can do that." That isn't the point. The point is having a command you are asking people to run as root hosted on a plain http site doesn't leave a good impression as anyone between the client and server could transparently modify the data. That is why the packages in say the Debian or CentOS repos are PGP signed.

**Comment by mahmut-spark** [comment]
@jhuckaby , thank you. please don't forget to update the project description with the github pages link :)

cronicle.net is redirecting for the www. only.

**Comment by mikeTWC1984** [comment]
I don't really see much problem in HTTP only. Why not just put nginx on the same machine and configure reverse proxy? Why not wrap your cronicle process in a container, to isolate it from the host machine? Running it as root is safer for my mind, otherwise you won't be able to limit access to FS for shell plug users (e.g. to discover config files, etc)
Regarding security - do not expose your cronicle to the world, there are likely some holes in it anyway (like in any other software), https won't help much here.

**Comment by tburnshrsd** [comment]
> I don't really see much problem in HTTP only. Why not just put nginx on the same machine and configure reverse proxy? Why not wrap your cronicle process in a container, to isolate it from the host machine? Running it as root is safer to my mind, otherwise you won't be able to limit access to FS for shell plug users (e.g. to discover config files, etc) Regarding security - do not expose your cronicle to the world, there are likely some holes in it anyway (like in any other software), https won't help much here.


The problem has been fixed and that isn't what we were talking about at all. We were talking about how http://cronicle.net was http only and at the bottom of the page contained a `curl | $some_interpreter`  to run as root.
