### ISSUE TITLE
Job Event Log via Discord

### ISSUE THREAD

**Issue by tokar86a** [jhuckaby/Cronicle#622]
Is that something i can include in the "web_hook_text_templates" settings? And how can i included that information if that's the case?

**Comment by tokar86a** [comment]
@jhuckaby Is that something i can do?

**Comment by jhuckaby** [comment]
The entire job event log?  No, because notifications are designed to be very short, and all on one line, and the job event log could be gigabytes in size.  See the Discord Webhook Integration Wiki for details on what you can customize:

https://github.com/jhuckaby/Cronicle/wiki/Discord-Webhook-Integration

You can include the job `[description]` property in your webhook text template, and you can populate that with whatever you want in your job, using the JSON STDIO API.  For e.g. inside a shell script job:

```sh
echo '{"description":"Put anything you want here!  Custom text!  Yay!"}'
```

Then, include the `[description]` macro in your webhook text template for successful job completion (it's already in the job failure one):

```js
"job_complete": "Job completed successfully on [hostname]: [event_title] -- [description] -- [job_details_url]",
```

This should show up in Discord.

Good luck!
