### ISSUE TITLE
Web UI doesn't load

### ISSUE THREAD

**Issue by KumarappanA** [jhuckaby/Cronicle#63]
Hello @jhuckaby,

Installation succeeded, I ran the setup and start as well in a single server setup.
I don't use nginx, just simple install, setup and start with default config.
When I try to load http://IP_ADDRESS:3012/, I just see the Cronicle logo and the footer, I don't see any content. Is the setup I'm following wrong?

Node v8.9.0
Npm v5.5.1
Cronicle v0.8.4
Browsers used: Chrome, Firefox and Opera.

**Comment by jhuckaby** [comment]
Hello there, and sorry for the confusion over this.  Since you are using nginx, you should read the doc section on [Load Balancers](https://github.com/jhuckaby/Cronicle#load-balancers).  Also, keep in mind that Cronicle is designed specifically to connect to servers via their local LAN IPs.  However, you can easily change this to use the server *hostname* instead.  What you want is to set this configuration directive:

https://github.com/jhuckaby/Cronicle#web_socket_use_hostnames

> Setting this parameter to 1 will force Cronicle's Web UI to connect to the back-end servers using their hostnames rather than IP addresses. This includes both AJAX API calls and Websocket streams. You should only need to enable this in special situations where your users cannot access your servers via their LAN IPs, and you need to proxy them through a hostname (DNS) instead. The default is 0 (disabled), meaning connect using IP addresses.

You actually have two choices here.  You can either change your server's hostname to something that resolves to its public IP address, *or* you can simply copy the server's hostname and paste into a local `/etc/hosts` file on your machine, and remap it locally to the public IP.

Either way, with the `web_socket_use_hostnames ` configuration directive set, Cronicle will connect to the server via the hostname rather than the IP.  Good luck, and sorry for the confusion!

**Comment by KumarappanA** [comment]
@jhuckaby I have mentioned that I don't use nginx. It's a simple setup with just install, setup and start scripts.

**Comment by KumarappanA** [comment]
@jhuckaby thanks it works fine now, hostname was the issue. Closing this issue.
