### ISSUE TITLE
Is possible to specify a frequency ?

### ISSUE THREAD

**Issue by pioardi** [jhuckaby/Cronicle#68]
Hi,
i have this requirement :
a job must run each 2 weeks ( on a specific day of the week ) , is actually possible to specify a job frequency ??? 
Thanks in advance

**Comment by jhuckaby** [comment]
There is no perfect way to do this, because Cronicle uses the "cron" system of years, months, month days and weekdays.  There is no "two week day", so it would be really difficult to natively support something like this.  However, there is a way to get very close to what you want:

You can use the "Custom" timing mode.  First, select the weekday you want your job to run on (Sunday in my example), then enable **two sets** of 7 days each, 7 days apart, one at the start of the month, and one starting on the 15th of the month.  So enable the following day checkboxes: 1st, 2nd, 3rd, 4th, 5th, 6th and 7th of the month, and the 15th, 16th, 17th, 18th, 19th, 20th and 21st.  It won't run on all these days because you've **also** specified to **only** run on Sundays (or whatever weekday you specify).  So then to finalize, select the desired hour and minute (4:00 AM in my example).  Screenshot:

<img width="716" alt="screenshot 2018-06-19 20 39 43" src="https://user-images.githubusercontent.com/700765/41636028-ee0f38c0-7400-11e8-94dd-bbe719e52244.png">

The idea here is that the scheduler timing algorithm must satisfy **all** your selections, in whatever categories.  So it must satisfy both "weekday == Sunday", **and** be either the 1st - 7th, or 15th - 21st of the month, **and** at 4:00 AM.  This should always fire exactly twice per month, on the weekday you specify, at the time you specify, every other week.

Now, as I said above, this isn't perfect, because there aren't exactly 4 weeks per month (except in February on non-leap years).  It's more like 4 weeks plus 0 - 3 days.  So every few months this will miss a week.  Specifically, if your weekday falls on the 29th, 30th or 31st of the month, then I believe it'll miss one week, but pick right up the next week.

Hope this helps, and I am sorry there isn't a cleaner way to do this.

\- Joe

**Comment by jhuckaby** [comment]
You could also check the 29th, 30th and 31st day checkboxes, which would prevent it from randomly skipping a week, but it would also cause it to error in the other direction: it would fire on two consecutive weeks, every few months.

**Comment by pioardi** [comment]
Hi @jhuckaby  ,
thanks a lot for your clarifications . For my requirements i need to customize Cronicle with a check on code .
This customization is based on concept of even/odd week starting from a Monday( 18 June 2018) . 

So adding two params(isBiWeeklyOdd and isBiWeeklyEven) to shell script , i can select the weekday/s , and then skip the job on odd weeks or even weeks .

![croniclefeatures](https://user-images.githubusercontent.com/15161576/41641109-7013d7f0-7464-11e8-91dc-c6c46198336e.PNG)



As you can see , i add other two features daysToExclude ( so i can exclude one or more specific days) and startDate/endDate (that specify the period in which the job should run ).

Let me know if you are interested to have these features in this repo .

NB : I have the code on a  private repo .

Thanks again .

**Comment by dol-leodagan** [comment]
@jhuckaby 
Are you relying on Paul Vixie's Cron implementation ?

In this Cron implementation, that is widely used, jobs are ran both on day of week matches and day of month matches if both are provided...

https://linux.die.net/man/5/crontab

> Note: The day of a command's execution can be specified by two fields - day of month, and day of week. If both fields are restricted (ie, aren't *), the command will be run when either field matches the current time. For example,
"30 4 1,15 * 5" would cause a command to be run at 4:30 am on the 1st and 15th of each month, plus every Friday.

**Comment by dol-leodagan** [comment]
Well if it's a design choice it's ok for me, I just think that it could be misleading for this edge case that is well known from Unix admins (and most of the time unexperienced users think that both DoW and DoM clauses need to match)

But I think the resulting message "On The 1st and 15th, on Fridays, at 4:30am" doesn't reflect that the 1st and 15th need to be Fridays...

**Comment by jhuckaby** [comment]
I will add something to the documentation that explains this difference from the Cron specification.  I do have an example in the docs which uses both weekdays and month days, in the [Event Timing Object](https://github.com/jhuckaby/Cronicle#event-timing-object) section, but it is somewhat buried, and doesn't explicitly call out the difference.

Thanks for pointing it out!

**Comment by jhuckaby** [comment]
Added new section in docs: [Cron Noncompliance](https://github.com/jhuckaby/Cronicle#cron-noncompliance)

Also linked to it from the [Ops Notes](https://github.com/jhuckaby/Cronicle#ops-notes) section, so hopefully Unix admins will read it.
