### ISSUE TITLE
Stuck on "waiting for masterserver" if new hostname has uppercase letter.

### ISSUE THREAD

**Issue by StefanBRas** [jhuckaby/Cronicle#82]
## Summary
Using upper-case when correcting hostname will make Cronicle get stuck on "Waiting for master server" even if the hostname has upper-case. Related to #36. Using only lowercase in global/server_groups/0 and/or get global/servers/0 fixes the issue.

I don't expect it to be fixed, maybe just documented somewhere as  it took me some (way too much) time to figure out. If not, hopefully people with the same problem will find this issue.

Cheers, great work on Cronicle. 

## Steps to reproduce the problem
Change hostname to something with an uppercase letter, try to use the fix in #36.

### Operating system and version?
Raspbian GNU/Linux 9 (stretch) running on a raspberry pi 3

### Node.js version?
v8.11.1

### Cronicle software version?
Version 0.8.15

### Are you using a multi-server setup, or just a single server?
Single server
### Are you using the filesystem as back-end storage, or S3/Couchbase?
Filesystem
### Can you reproduce the crash consistently?
Probably, haven't tried it more than this once
## Log Excerpts
Not really important, but this line made me realise the error
```
[1532300393.996][2018-07-23 00:59:53][rasppi][Cronicle][debug][4][Server not found in cluster -- waiting for a master server to contact us][]
```
Cronicle sees the hostname as "rasppi" eventhough it's "raspPi".

**Comment by jhuckaby** [comment]
Ah, thank you for the issue report, and I am very sorry you had to spend so much time troubleshooting this.  I am guessing I made a stupid assumption that server hostnames would always be lower-case, because all of mine are.  Sigh.

I will fix this as soon as I can.  Thanks again!

**Comment by StefanBRas** [comment]
No worries, the time i used on troubleshooting is nothing compare to how much time Cronicle saved me overall.

Though i feel like #36 could be referenced somewhere in the README under something like "Troubleshooting" or "Known Issues". It seems like something that can happen quite commonly and even though the fix is easy, it's something you'd never figure out yourself.

Could be that changing hostname is really unconventional and it's just me i guess.

**Comment by jhuckaby** [comment]
Yikes, so as it turns out, this issue runs **deep**.  There are so many places where I either assume the hostname is always lower-case, or just straight-up lower-case it, that it will take quite some time to fix, and test everything.  This goes well beyond Cronicle and into all my supporting modules, that are used by a number of other applications.  In short, I can't fix this issue quickly.

Basically, Cronicle **really** expects all the server hostnames to be lower-case internally, so when someone edits the raw storage records and makes them mixed case, everything falls apart.   To be fair, your own server hostnames can be mixed case and that's fine, but the raw storage records (which Cronicle writes to) need to be pre-lower-cased.  So this issue should only come into play when people are manipulating raw storage data on the CLI (which I HOPE is rare).

I will keep this issue open and on my TODO list.  I will also promote the information in #36 to a Troubleshooting Wiki, as you suggest.

Thank you very much for reporting this.  I will add this issue to the Roadmap as well, so it is not forgotten.

**Comment by jhuckaby** [comment]
New Wiki: https://github.com/jhuckaby/Cronicle/wiki/Troubleshooting

**Comment by traveltek-jnewall** [comment]
@jhuckaby Ive been having this issue recently and really cant figure out how to get the UI working. Ive tried everything possible to get it working and it is still saying waiting for master server. The configuration is fine for the master and slave server. We also have automation in place to restart the daemon if it fails. This is what in effect alerts us to issues and then seeing that the UI is not working. We have spun up new master servers to umpteen times and tried umpteen changes but still not having any luck at all.

**Comment by jhuckaby** [comment]
@traveltek-jnewall This issue is very old, and is about hostnames with upper-case letters in them.  Is that the problem you are having?  There is no easy fix, so I had to punt this until Cronicle v2 comes out.
