### ISSUE TITLE
Question: How to get local logs of a slave?

### ISSUE THREAD

**Issue by Taz4Git** [jhuckaby/Cronicle#86]
## Summary

Sometimes i get a message:
"Lost connectivity to server:XXXXX"
A few minutes after this message i got 
"Job # on server XXXXX failed with error: Aborted Job: Server 'XXXXX' shut down unexpectedly." in the Activity Log.

I am running a crontab on every slave, that checks status and restarts cronicle when it's not active.
But i want to locally log the reason for crashing, before i restart cronicle.
Is there any way to get the local latest logs of a slave?
Only the latest log if posible, not all logs described in https://github.com/jhuckaby/Cronicle#logs

Thanks in advance!

## Your Setup

1 master, 6 slaves.
All running the latest version of cronicle.

### Operating system and version?

master: Ubuntu 18.04 LTS
slaves: Ubuntu 16.04.4 LTS

### Node.js version?

master: 8.10.0
slaves: 8.11.3

### Cronicle software version?

 master and slaves: 0.8.17

**Comment by jhuckaby** [comment]
Yikes, that should not be happening at all.  The file you want is called `crash.log` on the server that crashed, and it can be found here:

```
/opt/cronicle/logs/crash.log
```

Note that every night at midnight (local server time) the logs will be archived (gzipped and stored) in whatever location you have set in your [log_archive_path](https://github.com/jhuckaby/Cronicle#log_archive_path) configuration property.  The default location is:

```
/opt/cronicle/logs/archives/[yyyy]/[mm]/[dd]/crash-[yyyy]-[mm]-[dd].log.gz
```

So if you want to find crashes from previous days, you can fill out the YYYY/MM/DD and look there, on the server that crashed.

If you could, please send ME the contents of your crash logs, because they will have a stack trace, and I can most likely track down why it crashed and fix it.

Thanks!

**Comment by Taz4Git** [comment]
Thank you for the reply.
I found the crashlog.
This is the content:

> Sun Jul 29 2018 02:31:47 GMT+0200 (CEST)
Error: spawn ENOMEM
    at _errnoException (util.js:992:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.execFile (child_process.js:212:15)
    at Object.exports.exec (child_process.js:142:18)
    at constructor.monitorServerResources (/opt/cronicle/lib/job.js:1643:6)
    at constructor.tick (/opt/cronicle/lib/engine.js:261:9)
    at emitNone (events.js:111:20)
    at __construct.emit (events.js:208:7)
    at __construct.tick (/opt/cronicle/node_modules/pixl-server/server.js:265:8)

I found my problem, but i'm not sure if the problem is (partly) in cronicle.
This is the scenario:

1 Event:
Timing: every 10 minutes.
Concurrency: 2
Timeout: 55 minutes

The script checks if it can export something.
If the result is true (mostly every hour) it will start another process. (which consumes 5gb (+/-70%) of my memory)
If the timeout kicks in, it kills the parent process, but it looks like the child process isn't killed.
So when the next hour comes, it will start another 5 gb consuming process, which will result in a memory shortage and this will also kill cronicle.

Hope this helps (if a part of the problem is in cronicle)

Kind regards

**Comment by jhuckaby** [comment]
Okay, thank you.  The problem is that your server is completely running out of memory, to such an extreme degree that Cronicle can't even spawn `ps` to get a list of running processes.  I've never actually seen a server in this bad of a state before.

I will go ahead and add a proper error handler to this spawn call to properly catch the error and avoid a hard crash, but I have to say, this is an extreme case.  What I mean is, if your server is really that starved for memory, something else will most definitely crash.  This just happened to be the straw that broke the camel's back, so to speak.  Cronicle just can't run without some amount of free memory on the server.

But thank you for reporting this.  Ideally Cronicle should be catching that error.
