### ISSUE TITLE
[ Control script not updating pid path ]

### ISSUE THREAD

**Issue by jerome83136** [jhuckaby/Cronicle#92]
Hi,

I have installed cronicle in a custom directory.

But it seems the control script does not take it into account.

The path to the PID stayed like this: (this is not the value I have configured in the configuration file)

```
# the path to your PID file
PIDFILE=$HOMEDIR/logs/cronicled.pid
```

Hope it helps

Best regards

**Comment by jhuckaby** [comment]
Hello, and thank you for the issue report.  Yeah, Cronicle isn't really designed to be installed into a custom directory, unless it's for a local developer installation, i.e. would only run in debug mode, where no PID file is used.

Unfortunately this is a bit tricky to fix, because the control script is a shell script, and it cannot (easily) read the configuration file to get the PID file location, if it has been customized.  I'll keep this issue open and add it to the roadmap for v2.0 tho.

Thanks!
